config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :recipes do
    resources :recipe_foods
  end

  resources :foods

  resources :shopping_lists, only: [:index]

  # Defines the root path route ("/") to the public_recipes controller's index action
  root "users#index"
  get '/foods', to: 'foods#index'
  get '/recipes', to: 'recipes#index'
  get '/public_recipes', to: 'public_recipes#index'
  
  delete '/recipes/:id', to: 'recipes#destroy', as: 'destroy_recipe'
  delete '/foods/:id', to: 'foods#destroy', as: 'destroy_food'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, Recipe
      can :create, Recipe
      can :destroy, Recipe, user_id: user.id

      can :read, Food
      can :create, Food
      can :destroy, Food, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 100 }, uniqueness: { scope: :user_id, message: 'already exists' }
  validates :price, presence: true
  validates :measurement_unit, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1000 }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :food, uniqueness: { scope: :recipe, message: 'already exists in this recipe' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy

  enum role: %i[user admin]

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @user = current_user
    @foods = @user.foods.includes(:user)
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:notice] = 'Food deleted successfully'
    redirect_back(fallback_location: root_path)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to foods_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @public_recipes = Recipe.where(public: true).includes(:user).order(created_at: :desc)
    @recipe_foods = RecipeFood.all
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe_food.recipe_id = params[:recipe_id]
    if @recipe_food.save
      flash[:notice] = 'Successfully added new ingredient'
      redirect_to recipe_path(params[:recipe_id])
    else
      flash[:alert] = 'Error adding the ingredient'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:notice] = 'Ingredient deleted successfully'
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    @user = current_user
    @recipes = @user.recipes.includes(:user)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      flash[:notice] = 'Successfully added new recipe'
      redirect_to recipes_path
    else
      flash[:alert] = 'Error adding the recipe'
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe.id), notice: 'Visibility updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe deleted successfully'
    redirect_back(fallback_location: root_path)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @recipe = Recipe.includes(:recipe_foods).where(user: @user)
    @recipe_foods = RecipeFood.where(recipe: @recipe).group_by { |recipe_food| recipe_food.food.name }
    @total_price = @recipe_foods.map do |_food, recipe_foods|
      recipe_foods.map do |recipe_food|
        recipe_food.quantity * recipe_food.food.price.to_i
      end.sum
    end.sum
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
  # In your view or helper file
  include ActionView::Helpers::NumberHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<section class="main-wrapper">
  <h2 class="main-heading">Foods</h2>
  <% if current_user == @user %>
    <%= link_to "New Food", new_food_path(current_user), class:'btn' %>
  <% end %>
  
  <% if @foods.empty? %>
    <h4 class="alert">No foods added yet.</h4>
  <% else %>
    <table class="food-table">
      <thead>
        <tr>
          <th colspan="2">Food</th>
          <th>Measurement Unit</th>
          <th>Price</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each_with_index do |food, index| %>
          <tr>
          <td colspan="2"><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <td>
            <% if can? :destroy, food %>
              <%= button_to 'Delete', destroy_food_path(food), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
            <% end %>
          </td>
          </tr>
        <% end %>
      <tbody>
    </table>
  <% end %>
<section class="main-wrapper">

app/views/foods/new.html.erb
<section class="new_food">
  <h2 class='main-heading'>Create New Food</h2>

  <%= form_with model: @food, class:"form_container" do |form| %>

    <div class="form_group">
      <%= form.label :name, "Food Name", class: "form_label" %>
      <%= form.text_field :name, class: "form_input" %>
    </div>

    <div class="form_group">
      <%= form.label :measurement_unit, class: "form_label" %>
      <%= form.text_field :measurement_unit, class: "form_input" %>
    </div>

    <div class="form_group">
      <%= form.label :price, "Price ($)", class: "form_label" %>
      <%= form.number_field :price, class: "form_input", value: number_to_currency(form.object.price) %>
    </div>

    <div class="form_group">
      <%= form.label :quantity, class: "form_label" %>
      <%= form.number_field :quantity, class: "form_input" %>
    </div>

    <%= form.submit class: "btn" %>
  <% end %>

  <%= link_to 'Back to Foods', foods_path, class: 'back-btn' %>
</section>

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <h2>Recipe App</h2>
  <ul class="nav-list">
    <% if user_signed_in? %>
      <li><%= link_to 'Home', root_path, class: "nav-btn" %></li>
    <% end %>
    <li><%= link_to 'Public Recipes', public_recipes_path, class: "nav-btn" %></li>
    <% if user_signed_in? %>
      <li><%= link_to 'Foods', foods_path, class: "nav-btn" %></li>
      <li><%= link_to 'Recipes', recipes_path, class: "nav-btn" %></li>
      <li><%= button_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-btn user-btn" %></li>
    <% else %>
      <li><%= link_to 'Log in', new_user_session_path, class: "nav-btn user-btn" %></li>
      <li><%= link_to 'Sign up', new_user_registration_path, class: "nav-btn user-btn" %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🍽 Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main>
      <% if flash[:notice] && !current_page?("/") %>
        <p class="notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert] && !current_page?("/") %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/public_recipes/index.html.erb
<section class="main-wrapper">
  <h1 class="main-heading">Public Recipes</h1>

  <ul class="recipe-list">
    <% @public_recipes.each do |recipe| %>
      <li class="recipe-container">
        <div class="recipe-heading">
          <h2><%= link_to recipe.name, recipe_path(recipe.id) %></h2>
          <h4><%= "By: #{recipe.user.name}" %></h4>
        </div>

        <div class="recipe-info">
          <p><%= "Total Food Items: #{recipe.foods.count}" %></p>
          <p><%= "Total Price: $#{@recipe_foods.where(recipe: recipe).map {|value| value.food.price.to_i * value.quantity}.sum}" %></p>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/recipe_foods/new.html.erb
<section class="add_new_ingredient">
  <h2 class='main-heading'>Add New Ingredient</h2>

  <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(params[:recipe_id]), method: :post, local: true, class: "form_container" do |form| %>

    <div class="form_group">
      <%= form.label :food_id, class: "form_label" %>
      <%= form.select :food_id, current_user.foods.all.map { |food| [food.name, food.id] }, {}, class: "form_input" %>
    </div>

    <div class="form_group">
      <%= form.label :quantity, class: "form_label" %>
      <%= form.number_field :quantity, class: "form_input" %>
    </div>

    <%= form.submit "Add Ingredient", class: "btn" %>
  <% end %>

  <%= link_to "Back to #{Recipe.find(params[:recipe_id]).name}", recipe_path(params[:recipe_id]), class: "back-btn" %>
</section>

app/views/recipes/index.html.erb
<section class="main-wrapper">
  <h1 class="main-heading">Recipes</h1>
  <%= link_to 'New Recipe', new_recipe_path, class:'btn new-recipe-btn' %>

  <% if @recipes.empty? %>
    <h4 class="alert">No recipes added yet.</h4>
  <% end %>

  <ul class="recipe-list">
    <% @recipes.each_with_index do |recipe, index| %>
      <li class="recipe-container">
        <div class="recipe-heading">
          <h2><%= link_to recipe.name, recipe_path(recipe) %></h2>
          <h4><%= truncate(recipe.description, length: 100) %></h4>
        </div>

        <% if can? :destroy, recipe %>
          <%= button_to 'Delete Recipe', destroy_recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn' %>
        <% end %>
      </li>
    <% end %>
  </ul>
</section>

app/views/recipes/new.html.erb
<section class="new_recipe">
  <h2 class='main-heading'>Create New Recipe</h2>

  <%= form_with model: @recipe, class: "form_container" do |form| %>

    <div class="form_group">
      <%= form.label :name, "Recipe Name", class: "form_label" %>
      <%= form.text_field :name, class: "form_input" %>
    </div>

    <div class="form_group">
    <%= form.label :preparation_time, "Preparation Time (hrs)", class: "form_label" %>
    <%= form.number_field :preparation_time, class: "form_input" %>
  </div>

    <div class="form_group">
      <%= form.label :cooking_time, "Cooking Time (hrs)", class: "form_label" %>
      <%= form.number_field :cooking_time, class: "form_input" %>
    </div>

    <div class="form_group">
      <%= form.label :description, class: "form_label" %>
      <%= form.text_area :description, class: "form_input" %>
    </div>

    <div class="field">
      <%= form.check_box :public, class: "form_input" %>
      <%= form.label :public, class: "form_label" %>
    </div>

    <%= form.submit class: "btn" %>
  <% end %>

  <%= link_to 'Back to Recipes', recipes_path, class: 'back-btn' %>
</section>

app/views/recipes/show.html.erb
<section class="main-wrapper recipe-details">
  <% if !current_user.nil? && current_user.id == @recipe.user_id %>
    <%= link_to 'Back to Recipes', recipes_path, class: 'btn' %>
  <% else %>
    <%= link_to 'Back to Public Recipes', public_recipes_path, class: 'btn' %>
  <% end %>

  <article class="heading_section">
    <h2 class="recipe_heading"><%=@recipe.name %></h2>

    <div class="recipe_details">
      <div class="preparation_public">
        <p class="preparation_time"><%= "Preparation Time: #{@recipe.preparation_time} hour"%></p>
        <% if !current_user.nil? && current_user.id == @recipe.user_id %>
          <%= form_for @recipe do |f| %>
            <%= f.check_box :public, id: "visibility-toggle", class: "visibility_toggle_input" %>
            <%= f.label :public, class: "visibility_toggle_lable", for: "visibility-toggle" %>
            <%= f.submit "Update Visibility", class: "btn" %>
          <%end%>
        <% end %>
      </div>
      <p><%= "Cooking Time: #{@recipe.cooking_time} hour"%></p>
      <p>Steps to prepare:</p>
      <p><%= @recipe.description %></p>
    </div>
  </article>

  <% if !current_user.nil? && current_user.id == @recipe.user_id %>
    <div class="buttons">
      <%= link_to 'Generate Shopping List', shopping_lists_path, class: 'btn' %>
      <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe.id), class: 'btn' %>
    </div>
  <%end%>

  <hr>

  <% if @recipe.recipe_foods.empty? %>
    <h4 class="alert">No ingredients added yet</h4>
  <% else %>
    <table class="food-table">
      <thead>
        <tr>
          <th colspan="2">Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
          <tr>
            <td colspan="2"> <%= recipe_food.food.name %></td>
            <td> <%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
            <td> $ <%= recipe_food.food.price.to_i * recipe_food.quantity %></td>
            <% if !current_user.nil? && current_user.id == @recipe.user_id %>
              <td>
                <%= button_to "Remove", recipe_recipe_food_path(@recipe, recipe_food.id), method: :delete, class:'btn delete-btn' %>
              </td>
            <% else %>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</section>

app/views/shopping_lists/index.html.erb
<section class="main-wrapper">
  <h1 class='main-heading'>Shopping list</h1>

  <article class="amount-value">
      <h3>Amount of food items to buy: <span><%= @recipe_foods.length %></span> </h3>
      <h3>Total value of food needed: <span>$<%= @total_price %> </span></h3>
  </article>

  <% if @recipe_foods.length.zero? %>
    <h4 class="alert">
      You don't have any food items in your shopping list.
    </h4>
      <%= link_to 'Back to Recipes', recipes_path, class: 'btn' %>
  <% else %>
    <table class="food-table">
      <thead>
        <tr>
          <th colspan="2">Food</th>
          <th>Quantity</th>
          <th>Total Price</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe_foods.each do |food, recipe_foods| %>
          <tr>
            <td colspan="2"><%= food %></td>
            <td>
              <% total_quantity = recipe_foods.map(&:quantity).sum %>
              <%= total_quantity %>
              <%= recipe_foods.first.food.measurement_unit %>
            </td>
            <td>
              <% total_price = recipe_foods.map { |recipe_food| recipe_food.quantity * recipe_food.food.price.to_f }.sum %>
              $ <%= total_price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</section>

app/views/users/index.html.erb
<section class="home-container">
  <div class="logged-user">
    <article class="user-info">
      <p>User</p>
      <p>Name: <%= current_user.name %></p>
      <p>Email: <%= current_user.email %></p>
    </article>

    <article class="welcome">
      <h1>We become what we consume!</h1>
      <h3>Explore our recipes 🍽</h3>
    </article>
  </div>
</section>